tasks:
  evolutionary_constraint:
    downsample_dataset:
      dataset_path: kuleshov-group/cross-species-single-nucleotide-annotation
      dataset_split: valid
      dataset_subdir: Evolutionary_constraint
      sample_size: 1000
    generate_logits:
      model_path: kuleshov-group/compo-cad2-l24-dna-chtk-c8192-v2-b2-NpnkD-ba240000
      device: cuda
      batch_size: 128
      token_idx: 255
      simulation_mode: true
    # Empty configurations are necessary to still include
    # base configs for steps with input_path and output_path
    generate_scores: {}
    compute_roc: {}
datasets:
  - path: kuleshov-group/cross-species-single-nucleotide-annotation
    sequence_length: 512
models:
  - path: kuleshov-group/compo-cad2-l24-dna-chtk-c8192-v2-b2-NpnkD-ba240000
    max_sequence_length: 8192
executor:
  prefix: /tmp/evolutionary_constraint
