name: plantcad2-evaluation

envs:
  HUGGING_FACE_HUB_TOKEN: null
  ARGS: ""

workdir: .

run: |
  set -ex

  echo "SKYPILOT_NUM_NODES: $SKYPILOT_NUM_NODES"
  echo "SKYPILOT_NUM_GPUS_PER_NODE: $SKYPILOT_NUM_GPUS_PER_NODE"
  echo "SKYPILOT_NODE_IPS: $SKYPILOT_NODE_IPS"
  echo "SKYPILOT_NODE_RANK: $SKYPILOT_NODE_RANK"

  source .venv/bin/activate
  python -m src.pipelines.plantcad2.evaluation.pipeline \
    --config_path src/pipelines/plantcad2/evaluation/configs/config.yaml \
    --tasks.evolutionary_constraint.generate_logits.simulation_mode false \
    ${ARGS}
