target: zB73v5

chroms:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

# this controls the amount of bp that is read/written from disk at once
# since we train on 128-bp windows, 512bp sounds reasonable
# for now having larger chunks reduces the number of files which is
# less burden on the filesystem
# in zarr v3 you'll have shards which would allow to have fast reads
# with a small number of files
# but last time we tried it was slow
chunk_size: 1024

phyloP: phyloP
phastCons: phastCons_0.05_12_0.3

output_hf_path: plantcad/andropogoneae_msa
