dataset_path: https://huggingface.co/datasets/plantcad/maize-allele-frequency/resolve/main/test.parquet

raw_data_path: hf://datasets/plantcad/maize-allele-frequency-raw-data/Maize_Hapmap3_Exclude_TE_PlantCAD_Zero_Shot_Scores.parquet

msa_path: ../../maize_msa_train/results/msa.zarr

models:
  - PlantCAD
  - MSA_empirical_LLR
