ensembl_vep:
  species: zea_mays
  cache_url: https://ftp.ebi.ac.uk/ensemblgenomes/pub/plants/release-62/variation/indexed_vep_cache/zea_mays_vep_62_Zm-B73-REFERENCE-NAM-5.0.tar.gz
  cache_version: 62

conservation_models:
  phastCons: ../maize_msa_train/phastCons.bw
  phyloP: ../maize_msa_train/phyloP.bw