# Lint with pre-commit
name: lint

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  checks:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.1